# Generated by Django 5.1.4 on 2025-01-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_cetagory_service_s_post_cetagory_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cetagory',
            name='title',
        ),
    ]
