# Generated by Django 5.1.4 on 2025-01-27 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_cetagory_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Default Heading', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='heading',
        ),
        migrations.AddField(
            model_name='service',
            name='service_headding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Service', to='mainapp.service_heading'),
        ),
    ]
